const {chromium}=require('C:/Users/Windows11/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Users/Windows11/AppData/Local/ms-playwright/chromium-1228/chrome-win64/chrome.exe'});try{
 const page=await browser.newPage();let posts=0;
 const external={task_id:'external-05',title:'八月已有利润任务',template:'profit',execution_state:'external_task',scope:{month:'2026-08'},checkpoint:{business_status:'needs_review'},external_task:{owner:'05',observed_at:'2026-09-09T06:35:00Z',observed_status:'已暂停执行，等待用户确认成本与广告资料；业务结果 needs_review'},result_url:'/api/orbit/tasks/external-05/artifacts/index.html',steps:[{key:'coverage',label:'结算覆盖',state:'pending'},{key:'report',label:'利润报告',state:'pending'}]};
 const internal={task_id:'internal',title:'图片审核',template:'publication',execution_state:'waiting_user',required_action:{kind:'review',label:'审核商品图片',url:'/product-workspace?offer_id=123&round=images'}};
 await page.route('**/*',r=>{const url=new URL(r.request().url());if(r.request().method()!=='GET')posts++;if(url.pathname.endsWith('/navigation'))return r.fulfill({json:{navigation:[]}});if(url.pathname.endsWith('/artifacts/index.html'))return r.fulfill({contentType:'text/html',body:'<h1>现有利润资料缺口：成本与广告</h1>'});if(url.pathname==='/api/orbit/tasks/external-05')return r.fulfill({json:{task:external,events:[]}});if(url.pathname==='/api/orbit/tasks')return r.fulfill({json:{tasks:[external,internal],executor:{connected:true}}});const file=path.join(root,'web',url.pathname==='/'?'task_workspace.html':url.pathname);return r.fulfill({contentType:file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html',body:fs.readFileSync(file)});});
 await page.route('**/api/orbit/tasks',r=>r.fulfill({json:{tasks:[external,internal],executor:{connected:true},domain_guard:{unresolved_operation_count:4,unattached_operation_count:3,locked_resource_count:19}}}));
 await page.route('**/api/orbit/operations-runtime',r=>r.fulfill({json:{execution_mode:'web-only',worker_enabled:false,dispatcher:{state:'stopped'}}}));
 await page.goto('http://127.0.0.1/');await page.waitForSelector('#attentionList a');assert.equal(await page.locator('#countAttention').textContent(),'1');assert.equal(await page.locator('#attentionList a').count(),1);assert.ok((await page.locator('#taskRows').textContent()).includes('历史观测，非实时'));
 assert.ok((await page.locator('#connection').textContent()).includes('4 条历史业务操作尚未完成回读，锁定 19 个资源'));
 await page.locator('#taskRows [data-detail="external-05"]').first().click();await page.waitForFunction(()=>document.querySelector('#detailBody').textContent.includes('原任务观测状态'));assert.ok((await page.locator('#detailBody').textContent()).includes(external.external_task.observed_status));assert.equal(await page.locator('#detailBody .steps li').count(),0);assert.equal(await page.locator('#inputForm, #retryTask, #cancelTask').count(),0);assert.ok((await page.locator('#detailBody').textContent()).includes('未同步步骤不代表尚未开展'));
 await page.locator('#detailBody a').click();assert.ok(page.url().endsWith('/artifacts/index.html'));assert.equal(posts,0);console.log('PASS historical observation outside attention, domain guard visible, exact result link, no fake pending/resume/POST');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
