const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const base=process.argv[2],out=process.argv[3],scenario=JSON.parse(fs.readFileSync(path.join(out,'scenario.json')));
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.ORBIT_BROWSER_EXECUTABLE});
 const context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage();
 const errors=[],requests=[],checks=[],responses=[],hitTests=[];let dashboard;
 async function hit(selector,label){
  const el=page.locator(selector).first();await el.scrollIntoViewIfNeeded();
  const result=await el.evaluate(el=>{const r=el.getBoundingClientRect(),x=r.x+r.width/2,y=r.y+r.height/2,h=document.elementFromPoint(x,y);return {rect:r.toJSON(),scrollY,viewport:{width:innerWidth,height:innerHeight},hit:h?.outerHTML,ok:!!h&&(h===el||el.contains(h))};});
  hitTests.push({label,...result});assert.ok(result.ok,JSON.stringify({label,...result}));
  if(result.viewport.width===390)await page.screenshot({path:path.join(out,label.replaceAll(' ','-')+'-viewport.png'),fullPage:false});
  return el;
 }
 async function shot(label,y){await page.evaluate(y=>scrollTo(0,y),y);await page.screenshot({path:path.join(out,label+'.png'),fullPage:false});hitTests.push({label,...await page.evaluate(()=>({scrollY,viewport:{width:innerWidth,height:innerHeight},nav:document.querySelector('#orbitSidebar').getBoundingClientRect().toJSON(),summary:document.querySelector('.current-review-summary').getBoundingClientRect().toJSON(),skip:document.querySelector('.skip-link').getBoundingClientRect().toJSON()}))});}
 await context.route('**/*',r=>new URL(r.request().url()).origin===new URL(base).origin?r.continue():r.abort());
 page.on('pageerror',e=>errors.push(String(e)));page.on('request',r=>requests.push({url:r.url(),method:r.method()}));
 page.on('response',async r=>{if(r.url().includes('/api/product-flow/preview'))responses.push(await r.json());});
 page.on('response',async r=>{if(r.url().includes('/api/product-workspace/dashboard'))dashboard=await r.json();});
 try{
  await page.goto(base+'/product-workspace?offer_id='+scenario.offer_id);
  await page.waitForSelector('.source-spec-option');
  await page.locator('#productDetail').scrollIntoViewIfNeeded();
  const metrics=await page.evaluate(()=>({height:document.documentElement.scrollHeight,rows:[...document.querySelectorAll('.source-spec-option')].map(r=>({top:r.getBoundingClientRect().top,bottom:r.getBoundingClientRect().bottom}))}));
  fs.writeFileSync(path.join(out,'density.json'),JSON.stringify(metrics));
  await page.screenshot({path:path.join(out,'facts-1440.png'),fullPage:true});
  await page.locator('#queueDisclosure>summary').click();
  await page.locator('#queueSearch').fill('tile');
  await page.locator('[data-queue-select]').check();
  assert.match(await page.locator('#queueSelectionCount').textContent(),/1/);
  await page.locator('#queueDisclosure>summary').click();
  await page.locator('#inspectCurrentReview').click();await page.locator('#reviewDetailDialog').waitFor();
  assert.match(await page.locator('#reviewDetailText').textContent(),/manual-intake/);
  await page.locator('#closeReviewDetail').click();
  await page.locator('#queueDisclosure>summary').click();
  assert.equal(await page.locator('#queueSearch').inputValue(),'tile');
  assert.equal(await page.locator('[data-queue-select]:checked').count(),1);
  await page.locator('#queueDisclosure>summary').click();
  checks.push('queue filter and selection survive detail return');
  await page.locator('#tab-targets').click();
  const selectedBefore=await page.locator('[name=publication_target]:checked').count();
  const firstTarget=await page.locator('[data-target-detail]').first().getAttribute('data-target-detail');
  await page.locator('[data-target-detail]').first().click();
  const detail=JSON.parse(await page.locator('#reviewDetailText').textContent());
  assert.deepEqual(detail.pricing,dashboard.pricing_review.target_pricing[firstTarget]);
  await page.locator('#closeReviewDetail').click();
  assert.equal(await page.locator('[name=publication_target]:checked').count(),selectedBefore);
  await page.screenshot({path:path.join(out,'targets-1440.png'),fullPage:true});
  await page.locator('#tab-images').click();await page.waitForSelector('[data-embedded-image-index]');
  await page.screenshot({path:path.join(out,'images-1440.png'),fullPage:true});
  assert.equal(await page.locator('[data-embedded-image-index][value=keep]:checked').count(),0,'pending images must not be preselected keep');
  checks.push('pending not counted as keep');
  await page.locator('[data-embedded-image-index="0"][value=keep]').check();
  await page.locator('#tab-targets').click();await page.locator('#tab-images').click();
  assert.equal(await page.locator('[data-embedded-image-index][value=keep]:checked').count(),1);
  let refreshedDashboardReceived=false;
  const refreshedDashboard=page.waitForResponse(r=>r.url().includes('/api/product-workspace/dashboard')&&r.request().method()==='GET').then(r=>{refreshedDashboardReceived=true;return r;});
  await page.locator('#saveEmbeddedImageReviewButton').click();
  await page.waitForFunction(()=>document.querySelector('#embeddedImageReviewMessage').textContent.includes('已保存'));
  const savedReceiptPrecededReadback=!refreshedDashboardReceived;
  await refreshedDashboard;
  assert.equal(savedReceiptPrecededReadback,false,'saved receipt must follow the authoritative dashboard readback');
  await page.waitForFunction(()=>{const el=document.querySelector('.current-review-summary');return !!el&&el.getClientRects().length>0&&el.getBoundingClientRect().height>0;});
  checks.push('explicit one-image keep persisted through real consumer');
  await page.setViewportSize({width:390,height:844});
  await shot('viewport-390-top',0);
  await shot('viewport-390-scroll',300);
  const summaryHit=await page.locator('.current-review-summary').evaluate(el=>{const r=el.getBoundingClientRect(),h=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return {scrollY,ok:el===h||el.contains(h),hit:h?.outerHTML};});
  hitTests.push({label:'summary center at scroll 300',...summaryHit});assert.ok(summaryHit.ok);
  await (await hit('#orbitMenu','mobile navigation open')).click();
  assert.equal(await page.locator('#orbitMenu').getAttribute('aria-expanded'),'true');
  await hit('#orbitCoreNav a','mobile navigation link');
  await (await hit('#orbitMenu','mobile navigation close')).click();
  assert.equal(await page.locator('#orbitMenu').getAttribute('aria-expanded'),'false');
  await (await hit('#inspectCurrentReview','mobile summary detail')).click();
  await (await hit('#closeReviewDetail','mobile detail close')).click();
  assert.equal(await page.locator('#reviewDetailDialog').evaluate(el=>el.open),false);
  await (await hit('#tab-targets','mobile targets tab')).click();
  assert.ok(await page.locator('[data-target-detail]').first().isVisible());
  await (await hit('#tab-images','mobile images tab')).click();
  await (await hit('[data-embedded-image-index="0"][value=remove]','mobile image remove')).check();
  await (await hit('[data-embedded-image-index="0"][value=keep]','mobile image keep')).check();
  await (await hit('#saveEmbeddedImageReviewButton','mobile image save')).click();
  await page.waitForFunction(()=>document.querySelector('#embeddedImageReviewMessage').textContent.includes('已保存'));
  await shot('viewport-390-after-save',300);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  await page.screenshot({path:path.join(out,'images-390.png'),fullPage:true});
  await page.locator('#tab-facts').click();
  await page.locator('.sku-commercial-input').last().scrollIntoViewIfNeeded();
  assert.ok(await page.locator('.sku-commercial-input').last().isVisible());
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  await page.screenshot({path:path.join(out,'facts-390.png'),fullPage:true});
  checks.push('details return preserves targets and narrow SKU controls remain reachable');
  await page.setViewportSize({width:1440,height:900});
  const before=JSON.parse(JSON.stringify(dashboard.product));
  const keys=await page.locator('[name=selected_sku_key]').evaluateAll(es=>es.map(e=>e.value));
  const edited=keys[1],removed=keys[5];
  for(const [field,value] of Object.entries({cost_cny:'12.34',weight_kg:'0.789',length_cm:'31',width_cm:'22',height_cm:'9'}))await page.locator(`[data-sku-key="${edited}"][data-commercial-field="${field}"]`).fill(value);
  await page.locator(`[name=selected_sku_key][value="${removed}"]`).uncheck();
  const savedResponse=page.waitForResponse(r=>r.url().includes('/api/product-workspace/facts')&&r.request().method()==='POST');
  await (await hit('#factsEditSaveButton','facts save')).click();
  const response=await savedResponse;assert.equal(response.status(),200,await response.text());
  await page.waitForFunction(()=>document.querySelector('#factsEditMessage').textContent.includes('已核对并保存'));
  const readback=await page.request.get(base+'/api/product-workspace/dashboard?offer_id='+scenario.offer_id);assert.equal(readback.status(),200);
  const after=await readback.json();
  fs.writeFileSync(path.join(out,'FACTS_READBACK.json'),JSON.stringify({before,after,edited,removed,keys},null,2));
  await page.reload({waitUntil:'networkidle'});await page.locator('#tab-facts').click();await page.waitForSelector('.source-spec-option');
  assert.equal(await page.locator(`[data-sku-key="${edited}"][data-commercial-field="cost_cny"]`).inputValue(),'12.34');
  for(const [field,value] of Object.entries({weight_kg:'0.789',length_cm:'31',width_cm:'22',height_cm:'9'}))assert.equal(await page.locator(`[data-sku-key="${edited}"][data-commercial-field="${field}"]`).inputValue(),value);
  assert.equal(await page.locator(`[name=selected_sku_key][value="${removed}"]`).isChecked(),false);
  await page.waitForLoadState('networkidle');
  checks.push('six-SKU facts edited and saved through actual Handler, HTTP readback and reload');
  assert.deepEqual(errors,[]);
 }catch(e){checks.push({error:String(e),body:await page.locator('body').innerText()});await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});process.exitCode=1;console.error(e);}
 fs.writeFileSync(path.join(out,'DENSE_BROWSER.json'),JSON.stringify({checks,errors,requests,responses,hitTests},null,2));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(2);});
