'use strict';
const fs=require('fs'),path=require('path');
const {chromium}=require(process.env.ORBIT_PLAYWRIGHT||'C:/Users/Windows11/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out=path.resolve(process.argv[2]),fixture=JSON.parse(fs.readFileSync(path.join(out,'preview.json'))),base=new URL(fixture.url);
if(base.hostname!=='127.0.0.1'||['8765','8766'].includes(base.port))throw Error('Own preview required');
const results=[],requests=[],responses=[],blocked=[],errors=[],htmlResponses=[];
const check=(ok,name,detail)=>{results.push({name,ok:!!ok,detail});if(!ok)throw Error(name+' '+JSON.stringify(detail));};
const pause=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
 const browser=await chromium.launch({...(process.env.ORBIT_BROWSER_EXECUTABLE?{executablePath:process.env.ORBIT_BROWSER_EXECUTABLE}:{channel:'chrome'}),headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:900},acceptDownloads:true});
 async function secure(c){await c.route('**/*',r=>{const u=new URL(r.request().url());if(['blob:','data:'].includes(u.protocol))return r.continue();if(u.origin!==base.origin){blocked.push(u.href);return r.abort();}requests.push({method:r.request().method(),url:u.href});return r.continue();});}
 await secure(context);const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('response',async r=>{if(r.request().method()==='POST'){try{responses.push({status:r.status(),payload:await r.json()});}catch{}}});
 const txt=id=>page.locator('#'+id).innerText();
 const imported={};
 async function importProfile(name,save=false){await page.locator('#configure').click();await page.locator('#profileFile').setInputFiles(fixture.profiles[name]);await page.waitForFunction(()=>document.querySelector('#profilePreview').textContent.includes('schema_version'));await page.waitForFunction(()=>document.querySelector('#profileName').value!=='' );await pause(50);imported[name]=await page.locator('#profileSelect').inputValue();if(save)await page.locator('#saveProfile').click();await page.locator('[data-close="profileDialog"]').click();}
 async function review(){const response=page.waitForResponse(r=>r.url().endsWith('/captured-review')&&r.request().method()==='POST');await page.locator('#reviewButton').click();const r=await response;await page.waitForFunction(()=>!document.querySelector('#reviewButton').disabled);return {status:r.status(),payload:await r.json()};}
 async function screenshot(name){await page.screenshot({path:path.join(out,name+'.png')});}
 page.on('response',async response=>{if(response.url().endsWith('/report-view')){const body=await response.body();htmlResponses.push({status:response.status(),url:response.url(),request:response.request().postData(),body_sha256:require('node:crypto').createHash('sha256').update(body).digest('hex')});fs.writeFileSync(path.join(out,'html-responses.json'),JSON.stringify(htmlResponses,null,2));}});
 try{
  if(fixture.full_handler){
   for(const [width,height] of [[1440,900],[390,844]]){
    await page.setViewportSize({width,height});
    await page.goto(new URL('/knowledge',base).href);await page.locator('.knowledge-row').first().waitFor();
    if(width===390)await page.locator('#orbitMenu').click();
    await page.locator('#orbitCoreNav a[href="/product-workspace"]').first().click();
    await page.waitForSelector('#productFactsForm',{state:'attached'});
    const profit=await context.request.get(new URL('/profit',base).href,{maxRedirects:0});check(profit.status()===200&&(await profit.text()).includes('/profit-original/artifacts/profit_reports_monthly/2026-07/index.html'),`profit hub retains July archive link ${width}`);
    if(width===390)await page.locator('#orbitMenu').click();
    await page.locator('#orbitCoreNav a[href="/supply-chain/"]').click();await page.waitForSelector('.sku-summary');
    check(await page.locator('.sku-summary').count()===8,`actual knowledge product finance synthetic supply chain ${width}`);
    await page.goBack();await page.waitForSelector('#productFactsForm',{state:'attached'});
    await page.goBack();await page.locator('.knowledge-row').first().waitFor();
    check(new URL(page.url()).pathname==='/knowledge',`actual return to knowledge ${width}`);
    await screenshot(`combined-knowledge-return-${width}`);
   }
   await page.setViewportSize({width:1440,height:900});
   await page.goto(new URL('/product-workspace',base).href);
   const profit=await context.request.get(new URL('/profit',base).href,{maxRedirects:0});
    check(profit.status()===200&&(await profit.text()).includes('/profit-original/artifacts/profit_reports_monthly/2026-07/index.html'),'actual full Handler product to profit hub and July archive');
  }
  await page.goto(fixture.url);await page.locator('#orbitCoreNav a[aria-current="page"][href="/profit"]').waitFor();
  check(!requests.some(r=>r.method==='POST'),'opening has no business POST');check(await txt('metricProfit')==='—','unselected money unknown');await screenshot('empty-1440');
  await importProfile('ready',true);check(!requests.some(r=>r.method==='POST'),'profile import/save does not calculate');
  const ready=await review(),report=ready.payload.reports.tiktok.report;
  check(ready.status===200&&report.order_lines.length===24,'actual consumer yields 24 order lines');
  check(await txt('metricProfit')===Number(report.totals.profit_cny).toFixed(2),'visible amount equals actual consumer',report.totals);
  check((await txt('modeLabel')).includes('估算广告'),'estimated kind visible');
  check((await txt('orderRows')).includes('TEST-9000')&&(await txt('orderRows')).includes('fixture'),'raw SKU and shop identity visible');
  check(await page.locator('#orderRows tr').first().locator('td').nth(2).innerText()==='— THB','absent buyer cash amount stays unknown');
  const visibleRows=await page.locator('#orderRows tr').evaluateAll(rows=>rows.filter(r=>r.getBoundingClientRect().bottom<=innerHeight&&r.getBoundingClientRect().top>=0).length);
  check(visibleRows>=10,'1440x900 shows at least 10 actual rows',visibleRows);await screenshot('ready-1440');
  const jsonDownload=page.waitForEvent('download');await page.locator('#exportJson').click();const json=JSON.parse(fs.readFileSync(await (await jsonDownload).path(),'utf8'));check(json.reports.tiktok.report.report_id===report.report_id&&json.scope.shop_id==='fixture','JSON export binds actual report and scope');
  await page.locator('#orderRows input').first().check();await page.locator('#orderSearch').fill('no-match');check((await txt('rowCount')).includes('筛选外 1')&&!await page.locator('#exportCsv').isDisabled(),'hidden selected export scope remains explicit');const csvDownload=page.waitForEvent('download');await page.locator('#exportCsv').click();const csv=fs.readFileSync(await(await csvDownload).path(),'utf8');check(csv.includes(report.report_id)&&csv.includes('realized_settlement_with_estimated_ads')&&csv.includes(ready.payload.captured_inputs.evidence_sha256)&&csv.split('\r\n').length===2,'selected CSV keeps real row, kind and source hash');await page.locator('#orderSearch').fill('');
  await page.locator('#configure').click();const originalSelection=await page.locator('#profileSelect').inputValue();await page.locator('#profileFile').setInputFiles({name:'invalid-profile.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...JSON.parse(fs.readFileSync(fixture.profiles.ready)),api_key:'SYNTHETIC-FORBIDDEN-FIELD'}))});await page.waitForFunction(()=>!document.querySelector('#profileError').hidden);check((await txt('profileError')).includes('不支持的配置字段')&&await page.locator('#profileSelect').inputValue()===originalSelection,'unknown credential field rejected without replacing selection');const profileDownload=page.waitForEvent('download');await page.locator('#exportProfile').click();const exportedProfile=JSON.parse(fs.readFileSync(await(await profileDownload).path(),'utf8'));check(exportedProfile.schema_version==='profit-captured-profile/v1'&&!('api_key'in exportedProfile)&&exportedProfile.evidence_path===JSON.parse(fs.readFileSync(fixture.profiles.ready)).evidence_path,'profile export preserves selected paths without invented picker path');await page.locator('[data-close="profileDialog"]').click();
  const beforeReload=requests.filter(r=>r.method==='POST').length;await page.reload();await page.waitForFunction(()=>document.querySelector('#profileSelect').value!=='');check(requests.filter(r=>r.method==='POST').length===beforeReload,'saved profile reload does not calculate');check(await txt('metricProfit')==='—','reload does not pretend old money is current');
  await review();await page.locator('#periodEnd').fill('2026-08-08');await page.locator('#periodEnd').dispatchEvent('change');check(await txt('metricProfit')==='—'&&await page.locator('#exportJson').isDisabled(),'changed input invalidates amount/export');await page.locator('#periodEnd').fill('2026-08-09');await page.locator('#periodEnd').dispatchEvent('change');
  await importProfile('partial');const partial=await review();check(partial.payload.reports.tiktok.report.order_lines.length===1,'actual partial retains one valid line');check((await txt('statusLabel')).includes('部分'),'partial status explicit');await page.locator('#tab-issues').click();check((await txt('issueRows')).includes('catalog_scope_mismatch'),'actual scope issue visible');await screenshot('partial-issues-1440');
  await page.locator('#tab-orders').click();await importProfile('empty');await review();check(await txt('metricProfit')==='—'&&await page.locator('#orderRows tr').count()===0,'actual empty is unknown money');
  await importProfile('missing');const missing=await review();check(missing.status===400&&(await txt('errorBanner')).includes('captured_input_check_failed'),'actual HTTP failure exits loading with error code');check(await txt('metricProfit')==='—','failure never becomes zero');
  await importProfile('slow');await page.locator('#reviewButton').click();await importProfile('empty');await review();await pause(1000);check(await txt('metricProfit')==='—'&&await page.locator('#orderRows tr').count()===0,'late old response cannot replace new profile');
  await importProfile('conflict');await review();check(await txt('metricProfit')==='—','unselected conflict yields unknown');await page.locator('#configure').click();await page.locator('#temporaryCost').check();await page.locator('#fxOverrides').fill('{"THB":"0.3"}');await page.locator('[data-close="profileDialog"]').click();const assumed=await review();check(assumed.payload.cost_policy.temporary_assumptions_selected===true&&assumed.payload.fx_provenance.input_source==='operator_override','actual consumer receives explicit assumptions and FX');await page.locator('#tab-sources').click();check((await txt('sourceSummary')).includes('人工覆盖')&&(await txt('sourceSummary')).includes('已选择'),'assumption provenance visible');await screenshot('assumptions-1440');
  await page.locator('#tab-versions').click();check((await txt('historyStatus')).includes('未选择'),'unselected approval index stays explicit');
  await page.locator('#tab-orders').click();await importProfile('formula');const formula=await review();await page.locator('#negativeOnly').check();check(await page.locator('#orderRows tr').count()===formula.payload.reports.tiktok.report.order_lines.filter(r=>Number(r.profit_cny)<0).length,'negative filter uses real calculated rows');await page.locator('#negativeOnly').uncheck();const safeDownload=page.waitForEvent('download');await page.locator('#exportCsv').click();const safeCsv=fs.readFileSync(await(await safeDownload).path(),'utf8');check(safeCsv.includes("'=SUM(1,1)"),'CSV neutralizes actual formula-like order identity');
  await importProfile('cash');const cash=await review();check(cash.payload.reports.tiktok.report.order_lines[0].settlement.buyer_cash_paid_product_amount_local==='180'&&await page.locator('#orderRows tr').first().locator('td').nth(2).innerText()==='180.00 THB','cash-paid column uses actual cash product amount, not sales 200');
  await importProfile('coverage-gap');const gap=await review();await page.locator('#tab-sources').click();check(gap.payload.coverage.status==='unknown'&&(await page.locator('#coverageRows tr').first().innerText()).includes('未证明'),'missing final day is unknown through actual HTTP/UI');await screenshot('coverage-gap-1440');
  await importProfile('zero');const zero=await review();check(zero.payload.coverage.days.every(d=>d.settlements.count===0)&&await txt('metricProfit')==='—','complete zero settlements does not invent zero profit');
  await importProfile('coverage');const covered=await review();check(covered.payload.history.entries.length===2,'actual approved index excludes other site and shop');
  const firstReview=covered.payload.review_id;await page.locator('#configure').click();await page.locator('#fxOverrides').fill('{"THB":"0.3"}');await page.locator('[data-close="profileDialog"]').click();const updated=await review();
  check(updated.payload.review_id!==firstReview&&updated.payload.approval_status==='REVIEW_ONLY','new FX calculation stays review and retains old version');
  for(const width of [1440,390]){
   await page.setViewportSize({width,height:width===390?844:900});await page.locator('#tab-sources').click();
   check((await txt('coverageClocks')).includes('2026-08-10T00:00:00+07:00'),'actual source cutoff visible '+width);
   check((await page.locator('#coverageRows tr').first().locator('td').nth(2).innerText())==='0'&&(await page.locator('#coverageRows tr').first().innerText()).includes('2026-08-09'),'proven final-day zero visible '+width);if(width===390)await page.locator('#coverageSummary').scrollIntoViewIfNeeded();await screenshot('coverage-'+width);
   await page.locator('#tab-versions').click();check(await page.locator('#approvedRows button').count()===2,'two original approved versions visible '+width);
   await page.locator('#approvedRows button').first().click();await page.locator('#reportDialog').waitFor({state:'visible'});
   await page.locator('#reportDialog summary').click();const approved=JSON.parse(await txt('reportEvidence'));check(approved.approval_status==='APPROVED'&&approved.report_sha256===covered.payload.history.entries[0].report_sha256,'open exact approved original '+width);await page.locator('#reportDialog summary').click();
   await page.frameLocator('#reportFrame').locator('body').filter({hasText:approved.report_id}).waitFor();check((await page.frameLocator('#reportFrame').locator('body').innerText()).includes(approved.report_id),'actual original renderer report identity visible '+width);check(await page.frameLocator('#reportFrame').locator('body').evaluate(e=>getComputedStyle(e).fontFamily.includes('system-ui')),'original renderer styles applied '+width);await screenshot('approved-open-'+width);await page.locator('[data-close="reportDialog"]').click();
   const prior=page.locator('#versionRows .version').filter({hasText:firstReview});await prior.locator('button').click();
   await page.locator('#reportDialog summary').click();const old=JSON.parse(await txt('reportEvidence'));check(old.review_id===firstReview&&old.reports.tiktok.report.report_id===covered.payload.reports.tiktok.report.report_id&&old.approval_status==='REVIEW_ONLY','old session version opens original bytes '+width);await page.locator('#reportDialog summary').click();await page.locator('[data-close="reportDialog"]').click();
   check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'coverage/history no page overflow '+width);await screenshot('history-'+width);
  }
  await page.locator('#tab-orders').click();await page.locator('#profileSelect').selectOption(imported.ready);await review();
  await page.locator('#tab-versions').click();await page.locator('#versionRows button').first().click();await page.frameLocator('#reportFrame').locator('tbody tr').first().waitFor();check(await page.frameLocator('#reportFrame').locator('tbody tr').count()===24,'open current 24-line report through bounded local renderer');await page.locator('[data-close="reportDialog"]').click();
  for(const width of [1440,390]){await page.setViewportSize({width,height:width===390?844:900});for(const tab of ['orders','issues','sources','versions']){await page.locator('#tab-'+tab).click();await page.evaluate(()=>scrollTo(0,0));check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'no page overflow '+width+' '+tab);await screenshot(tab+'-'+width);} }
  await page.locator('#tab-orders').click();await page.locator('#orbitMenu').click();check(await page.locator('#orbitCoreNav a[aria-current="page"]').isVisible(),'mobile data nav visible');await page.keyboard.press('Escape');

  async function sku(name){await importProfile(name);const waiting=page.waitForResponse(r=>r.url().endsWith('/captured-review')&&r.request().method()==='POST');await page.locator('#skuEvidence').click();await waiting;await page.waitForFunction(()=>!document.querySelector('#skuRefresh').disabled);const count=await page.locator('#skuChoice option').count();check(count===2,'SKU choices exclude same-name same-suffix cross shop/platform '+name,count);const selected=page.waitForResponse(r=>r.url().endsWith('/captured-review')&&r.request().method()==='POST');await page.locator('#skuChoice').selectOption('0');const response=await selected;await page.locator('#skuEstimate').waitFor();return await response.json();}
  check(await page.locator('a[href="/sku-profit"]').count()===0,'old live SKU link replaced by local entry');
  for(const width of [1440,390]){
   await page.setViewportSize({width,height:width===390?844:900});
   const evidence=await sku('sku-ready');
   check(evidence.estimate.profit_cny===6&&evidence.listing.amount==='250'&&evidence.recent.median===200,'actual SKU pure estimate and separate prices '+width);
   const body=await txt('skuBody');check(body.includes('250.00 THB')&&body.includes('200.00 THB')&&body.includes('listing-1')&&body.includes('sample-1'),'distinct price sources visible '+width);
   check(body.includes('非结算事实')&&body.includes('净结算内平台费不再扣除')&&body.includes('6.00 CNY'),'estimate label and no duplicate platform fee basis '+width);
   check(body.includes('Product product')&&body.includes('Variant variant')&&body.includes('Seller SKU TEST-9000'),'complete selected identity visible '+width);
   check(await page.locator('.sku-picture img').evaluate(e=>e.complete&&e.naturalWidth===80),'bounded local PNG displayed '+width);
   check(await page.locator('#skuDialog').evaluate(e=>e.scrollWidth<=e.clientWidth+1),'SKU dialog no horizontal overflow '+width);
   await screenshot('sku-ready-'+width);await page.locator('#skuEstimate').scrollIntoViewIfNeeded();await screenshot('sku-estimate-'+width);
   const p=JSON.parse(fs.readFileSync(fixture.profiles['sku-ready'],'utf8'));
   const endpoint=new URL('/api/profit-center/captured-review',base).href;
   for(const identity of [{...evidence.identity,shop_key:'other'},{...evidence.identity,platform:'shopee'},{...evidence.identity,seller_sku:'9000'}]){const response=await context.request.post(endpoint,{headers:{Origin:base.origin},data:{profile:p,mode:'sku',sku_identity:identity}});const v=await response.json();check(response.status()===400&&v.estimate===null,'actual HTTP cross-scope/suffix refused '+width+' '+JSON.stringify(identity));}
   const file=path.resolve(p.sku_evidence_path);if(!file.startsWith(path.join(out,'inputs')+path.sep))throw Error('Synthetic file boundary');const original=fs.readFileSync(file);const changed=JSON.parse(original);changed.entries[0].listing.amount='999';fs.writeFileSync(file,JSON.stringify(changed));
   fs.writeFileSync(path.join(out,'sku-mutation-'+width+'.json'),JSON.stringify({path:file,before_sha256:require('node:crypto').createHash('sha256').update(original).digest('hex'),after_sha256:require('node:crypto').createHash('sha256').update(fs.readFileSync(file)).digest('hex'),reason:'synthetic pinned-source mutation control'},null,2));
   try{const waiting=page.waitForResponse(r=>r.url().endsWith('/captured-review')&&r.request().method()==='POST');await page.locator('#skuRefresh').click();const v=await(await waiting).json();await page.waitForFunction(()=>document.querySelector('#skuStatus').textContent.includes('旧估算已失效'));check(v.estimate===null&&await page.locator('#skuEstimate').count()===0&&(await txt('skuStatus')).includes('sku_source_changed'),'changed source clears previous SKU estimate '+width);await screenshot('sku-source-changed-'+width);}finally{fs.writeFileSync(file,original);}
   await page.locator('[data-close="skuDialog"]').click();
   for(const name of ['conflict','missing','no-cost']){const v=await sku('sku-'+name);check(v.estimate===null&&(await txt('skuEstimate')).includes('未知'),'incomplete SKU keeps estimate unknown '+width+' '+name);check((await txt('skuBody')).includes('商品图未知'),'missing image explicit '+width+' '+name);if(name==='conflict'){await page.getByText('成本候选、冲突与版本',{exact:true}).click();check(v.gaps.includes('cost_unresolved')&&v.cost.candidates.length===2&&v.cost.issues.length>0,'cost conflict provenance visible '+width,v.cost);await page.getByText('成本候选、冲突与版本',{exact:true}).click();}if(name==='missing')check((await txt('skuBody')).includes('n=0')&&v.listing===null,'empty recent samples and absent listing distinct '+width);await screenshot('sku-'+name+'-'+width);await page.locator('[data-close="skuDialog"]').click();}
  }

  for(const width of [1440,390]){
   await page.setViewportSize({width,height:width===390?844:900});
   const v=await sku('waterfall-full'),w=v.waterfall;
   check(w.prior.with_affiliate.estimate.profit_cny===15&&w.prior.no_affiliate.estimate.profit_cny===18,'real prior model scenarios '+width);
   const withPrior=page.locator('.prior-fee[data-scenario="with_affiliate"]'),withoutPrior=page.locator('.prior-fee[data-scenario="no_affiliate"]');
   check((await withPrior.innerText()).includes('额外费封顶：是')&&(await withPrior.innerText()).includes('15.00 CNY'),'captured cap and actual prior result visible '+width);
   check((await withoutPrior.innerText()).includes('18.00 CNY')&&await withPrior.locator('.fee-row').count()===13,'all prior components rendered '+width);
   await withPrior.scrollIntoViewIfNeeded();await screenshot('waterfall-prior-'+width);
   const posterior=page.locator('.posterior-fee[data-scenario="all"]');check((await posterior.innerText()).includes('6.00 CNY')&&(await posterior.innerText()).includes('平台费已在净结算内，不再扣除'),'posterior net fees not double deducted '+width);await posterior.scrollIntoViewIfNeeded();await screenshot('waterfall-posterior-'+width);
   check((await txt('skuFeeObserved')).includes('完整分项吻合')&&(await txt('skuFeeObserved')).includes('未解释差额 0.00 THB'),'captured observed totals reconcile separately '+width);
   await page.locator('#skuFeeObserved').scrollIntoViewIfNeeded();await screenshot('waterfall-observed-'+width);
   check(await page.locator('#skuDialog').evaluate(e=>e.scrollWidth<=e.clientWidth+1),'waterfall no horizontal overflow '+width);
   const profile=JSON.parse(fs.readFileSync(fixture.profiles['waterfall-full'],'utf8')),file=path.resolve(profile.sku_evidence_path);if(!file.startsWith(path.join(out,'inputs')+path.sep))throw Error('Own waterfall input required');const original=fs.readFileSync(file);const changed=JSON.parse(original);changed.entries[0].waterfall.identity.shop_key='CHANGED';fs.writeFileSync(file,JSON.stringify(changed));
   try{const waiting=page.waitForResponse(r=>r.url().endsWith('/captured-review')&&r.request().method()==='POST');await page.locator('#skuRefresh').click();await waiting;await page.waitForFunction(()=>document.querySelector('#skuStatus').textContent.includes('旧估算已失效'));check(await page.locator('#skuWaterfall').count()===0,'identity/source mutation clears previous waterfall '+width);await screenshot('waterfall-changed-'+width);}finally{fs.writeFileSync(file,original);}
   await page.locator('[data-close="skuDialog"]').click();
   const partial=await sku('waterfall-partial');check(partial.waterfall.prior.with_affiliate.estimate===null&&(await page.locator('.prior-fee[data-scenario="with_affiliate"]').innerText()).includes('物流'),'partial prior preserves known rows and unknown result '+width);check((await txt('skuFeeObserved')).includes('部分费用未知')&&(await txt('skuFeeObserved')).includes('未解释差额 10.00 THB'),'partial observed difference is not invented fee '+width);await page.locator('#skuFeeObserved').scrollIntoViewIfNeeded();await screenshot('waterfall-partial-'+width);await page.locator('[data-close="skuDialog"]').click();
   await sku('waterfall-unknown');check((await txt('skuWaterfall')).includes('联盟状态未知 3 条')&&(await page.locator('.posterior-fee[data-scenario="no_affiliate"]').innerText()).includes('未知'),'unknown affiliation not merged into no-affiliate '+width);check((await page.locator('.prior-fee[data-scenario="no_affiliate"]').innerText()).includes('来源没有提供此情景'),'absent prior scenario not derived from other '+width);await page.locator('.prior-fee[data-scenario="no_affiliate"]').scrollIntoViewIfNeeded();await screenshot('waterfall-unknown-'+width);await page.locator('[data-close="skuDialog"]').click();
   await sku('waterfall-invalid');check((await txt('skuWaterfall')).includes('费用来源无效或已过期')&&await page.locator('.fee-row').count()===0,'expired source has no waterfall values '+width);await page.locator('#skuWaterfall').scrollIntoViewIfNeeded();await screenshot('waterfall-invalid-'+width);await page.locator('[data-close="skuDialog"]').click();
  }

  for(const width of [1440,390]){
   await page.setViewportSize({width,height:width===390?844:900});const v=await sku('sample-large'),audit=v.sample_audit;
   const count=async()=>JSON.parse(await page.locator('#sampleCounts').getAttribute('data-counts')),hist=async()=>JSON.parse(await page.locator('#sampleHistogram').getAttribute('data-histogram'));
   check(audit.counts.captured===37&&audit.counts.returned===37&&audit.rows.length===37,'actual full sample return '+width);
   const identities=[];for(let n=1;n<=4;n++){const rows=await page.locator('#sampleRows tr[data-row-key]').evaluateAll(rs=>rs.map(r=>r.dataset.rowKey));identities.push(...rows);const c=await count();check(c.page===n&&c.current_page===(n===4?7:10),'actual page count '+width+' '+n,c);if(n<4)await page.locator('#sampleNext').click();}
   check(identities.length===37&&new Set(identities).size===37&&identities.every((id,n)=>id===audit.rows[n].row_key),'all pages preserve exact captured identity/order '+width);
   check(await page.locator('#sampleNext').isDisabled(),'last page cannot advance '+width);await page.locator('#samplePrev').focus();await page.keyboard.press('Enter');check((await count()).page===3,'pagination keyboard action '+width);
   const allHist=await hist();check(allHist.count===37&&allHist.bins.reduce((n,b)=>n+b.count,0)===37,'histogram uses all filtered rows not current page '+width);
   const estimateBefore=await txt('skuEstimate'),postsBefore=requests.filter(r=>r.method==='POST').length;
   await page.locator('#sampleAffiliate').selectOption('with');await page.locator('#sampleProfit').selectOption('negative');await page.locator('#sampleOutlier').selectOption('true');
   const expected=audit.rows.filter(r=>r.affiliate_state==='with'&&r.profit_class==='negative'&&r.outlier===true);check((await count()).filtered===expected.length&&(await count()).page===1,'composed filters conserve population '+width);
   await page.locator('#sampleSearch').fill('SYNTHETIC-AUDIT-003');check((await count()).filtered===1&&(await hist()).count===1,'search composes with three filters '+width);
   check(await txt('skuEstimate')===estimateBefore&&requests.filter(r=>r.method==='POST').length===postsBefore,'display filters do not recalculate estimate '+width);await page.locator('#skuSampleAudit').scrollIntoViewIfNeeded();await screenshot('sample-filter-'+width);
   await page.locator('#sampleSearch').fill('no-such-synthetic-order');check((await count()).filtered===0&&(await hist()).bins.length===0&&(await hist()).unknown===0,'empty filtered set has no zero bucket '+width);
   await page.locator('#sampleSearch').fill('');for(const id of ['sampleAffiliate','sampleProfit','sampleOutlier'])await page.locator('#'+id).selectOption('all');
   await page.locator('#sampleProfit').selectOption('zero');check((await count()).filtered===audit.rows.filter(r=>r.profit_class==='zero').length,'zero class separate '+width);await page.locator('#sampleProfit').selectOption('all');await page.locator('#sampleAffiliate').selectOption('unknown');check((await count()).filtered===audit.rows.filter(r=>r.affiliate_state==='unknown').length,'unknown affiliate is a separate filter '+width);await page.locator('#sampleAffiliate').selectOption('all');
   await page.locator('#sampleRows button').first().click();check((await page.locator('#sampleDetail').innerText()).includes('"capture_index": 0')&&(await page.locator('#sampleDetail').innerText()).includes('"product_id": "product"'),'full raw identity and row evidence opens '+width);await page.locator('#sampleDetail summary').click();
   await page.locator('.sample-scroll').scrollIntoViewIfNeeded();await page.locator('.sample-scroll').evaluate(e=>e.scrollLeft=0);check(await page.locator('.sample-scroll').evaluate((e,width)=>width===390?e.scrollWidth>e.clientWidth:e.scrollWidth<=e.clientWidth+1,width),'desktop complete columns / mobile contained scroll '+width);
   if(width===390){await page.locator('.sample-scroll').focus();await page.keyboard.press('ArrowRight');await page.waitForFunction(()=>document.querySelector('.sample-scroll').scrollLeft>0);check(true,'mobile table keyboard scroll');}
   check(await page.locator('#skuDialog').evaluate(e=>e.scrollWidth<=e.clientWidth+1)&&await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'no dialog/page horizontal overflow '+width);await screenshot('sample-table-'+width);
   const profile=JSON.parse(fs.readFileSync(fixture.profiles['sample-large'],'utf8')),file=path.resolve(profile.sku_evidence_path);if(!file.startsWith(path.join(out,'inputs')+path.sep))throw Error('Own sample file required');const original=fs.readFileSync(file),changed=JSON.parse(original);changed.entries[0].samples.rows[0].order_id='SOURCE-CHANGED';fs.writeFileSync(file,JSON.stringify(changed));
   try{const wait=page.waitForResponse(r=>r.url().endsWith('/captured-review')&&r.request().method()==='POST');await page.locator('#skuRefresh').click();await wait;await page.waitForFunction(()=>document.querySelector('#skuStatus').textContent.includes('旧估算已失效'));check(await page.locator('#skuSampleAudit').count()===0&&await page.locator('#sampleHistogram').count()===0&&await page.locator('#sampleNext').count()===0,'source failure clears samples filters pages and chart '+width);await screenshot('sample-source-changed-'+width);}finally{fs.writeFileSync(file,original);}
   await page.locator('[data-close="skuDialog"]').click();
   await sku('sample-unknown');check((await count()).returned===37&&(await hist()).count===0&&(await hist()).unknown===37,'missing ad retains 37 raw rows and excludes unknown profits '+width);await page.locator('#sampleProfit').selectOption('unknown');check((await count()).filtered===37&&(await txt('sampleRows')).includes('未知'),'unknown profit filter does not become zero '+width);await page.locator('#skuSampleAudit').scrollIntoViewIfNeeded();await screenshot('sample-unknown-'+width);await page.locator('[data-close="skuDialog"]').click();await page.waitForFunction(()=>!document.querySelector('#skuSampleAudit'));
   await sku('sample-equal');check(await page.locator('#sampleProfit').inputValue()==='all'&&(await count()).page===1,'new capture resets filter/page state '+width);const equal=await hist();check(equal.bins.length===1&&equal.bins[0].count===37&&equal.min===equal.max,'identical profits occupy one complete bucket '+width);await page.locator('#sampleHistogram').scrollIntoViewIfNeeded();await screenshot('sample-equal-'+width);await page.locator('[data-close="skuDialog"]').click();
   const missingFees=await sku('sample-missing-fees');check(missingFees.estimate.n===37&&(await count()).returned===37&&missingFees.sample_audit.rows.every(r=>r.affiliate_state==='unknown'),'omitted optional fees retain raw rows and base estimate '+width);await page.locator('#sampleAffiliate').selectOption('unknown');check((await count()).filtered===37,'omitted fees visible as unknown affiliation '+width);await page.locator('#sampleAffiliate').selectOption('with');check((await count()).filtered===0,'omitted fees do not invent affiliate rows '+width);await page.locator('#sampleAffiliate').selectOption('unknown');await page.locator('#skuSampleAudit').scrollIntoViewIfNeeded();await screenshot('sample-missing-fees-'+width);await page.locator('[data-close="skuDialog"]').click();
   await sku('sample-empty');check((await count()).captured===0&&(await count()).returned===0&&(await count()).current_page===0&&(await hist()).count===0,'empty capture is zero records not zero profit '+width);await page.locator('#skuSampleAudit').scrollIntoViewIfNeeded();await screenshot('sample-empty-'+width);await page.locator('[data-close="skuDialog"]').click();
  }
  const edges=await page.evaluate(()=>[[],[null,null],[0,0],[-5,-5],[-3,-2,-1,0,1,2,3],[-1e308,0,1e308],[1,2,3,4,5]].map(values=>({values,result:ProfitSamples.histogram(values)})));
  check(edges.every(({values,result:h})=>h.count===values.filter(v=>typeof v==='number'&&Number.isFinite(v)).length&&h.bins.reduce((n,b)=>n+b.count,0)===h.count&&h.bins.every(b=>Number.isFinite(b.lower)&&Number.isFinite(b.upper))),'histogram empty/equal/negative/endpoints/extreme bounds conserve counts',edges);
  const bad=await browser.newContext({viewport:{width:390,height:844}});await secure(bad);await bad.addInitScript(()=>{Storage.prototype.setItem=function(){throw new DOMException('Quota','QuotaExceededError');};});const b=await bad.newPage();await b.goto(fixture.url);await b.locator('#configure').click();await b.locator('#profileFile').setInputFiles(fixture.profiles.ready);await b.waitForFunction(()=>!document.querySelector('#saveProfile').disabled);await b.locator('#saveProfile').click();check((await b.locator('#profileError').innerText()).includes('未能持久保存'),'storage failure explicitly says session only');await b.screenshot({path:path.join(out,'storage-failure-390.png')});await bad.close();
  check(!requests.some(r=>/settlement\/(config|pull)|sku-profit|profit-center\/weekly/.test(r.url)),'no automatic legacy FX or business pulls');check(!blocked.length&&!errors.length,'no external requests or JS exceptions',{blocked,errors});
  if(fixture.full_handler){
   await page.setViewportSize({width:1440,height:900});
   await page.locator('#orbitCoreNav a[href="/supply-chain/"]').click();await page.waitForSelector('.sku-summary');
   check(await page.locator('.sku-summary').count()===8,'same Handler finance to synthetic supply');await screenshot('combined-supply-1440');
   await page.goBack();await page.waitForSelector('#tab-orders');
   await page.locator('#orbitCoreNav a[href="/product-workspace"]').click();await page.waitForSelector('#productFactsForm',{state:'attached'});
   check(new URL(page.url()).pathname==='/product-workspace','same Handler supply history finance return to product');await screenshot('combined-return-product-1440');
  }
  const denied=await context.request.post(new URL('/api/profit-center/report-view',base).href,{headers:{Origin:'http://outside.invalid'},form:{report:'{}'}});check(denied.status()===403,'report view rejects foreign origin');
  const malformed=await context.request.post(new URL('/api/profit-center/report-view',base).href,{headers:{Origin:base.origin},form:{report:'{}'}});check(malformed.status()===400,'report view rejects malformed report');
 }catch(e){results.push({name:'uncaught',ok:false,detail:e.stack});fs.writeFileSync(path.join(out,'frame-failure.json'),JSON.stringify(await Promise.all(page.frames().map(async f=>({url:f.url(),html:await f.content(),body:await f.locator('body').evaluate(e=>({display:getComputedStyle(e).display,rect:e.getBoundingClientRect().toJSON()})).catch(()=>null)}))),null,2));await screenshot('failure');}
 finally{fs.writeFileSync(path.join(out,'browser-result.json'),JSON.stringify({fixture,renderer:'installed Chrome headless',results,requests,responses,blocked,errors},null,2));await browser.close();console.log(JSON.stringify({checks:results.length,failed:results.filter(r=>!r.ok)}));if(results.some(r=>!r.ok))process.exitCode=1;}
})();
